// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCconfiguration.Models;

namespace PCconfiguration.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PCconfiguration.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cooler Master Cosmos C700P",
                            Price = 421.43000000000001
                        },
                        new
                        {
                            Id = 2,
                            Name = "NZXT H710i",
                            Price = 169.99000000000001
                        },
                        new
                        {
                            Id = 3,
                            Name = "NZXT H200i",
                            Price = 99.989999999999995
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nanoxia Deep Silence 3",
                            Price = 80.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Corsair Carbide 275R",
                            Price = 79.989999999999995
                        });
                });

            modelBuilder.Entity("PCconfiguration.Models.CdDvd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CdDvds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ASUS ZenDrive Ultra Slim USB 2.0 External 8X",
                            Price = 36.140000000000001
                        },
                        new
                        {
                            Id = 2,
                            Name = "External DVD Drive Kilineo USB 3.0 CD Burner Reader",
                            Price = 25.989999999999998
                        },
                        new
                        {
                            Id = 3,
                            Name = "Asus Black 12X BD-ROM 16X DVD-ROM 48X CD-ROM SATA Internal Blu-Ray Drive",
                            Price = 58.710000000000001
                        },
                        new
                        {
                            Id = 4,
                            Name = "LG Electronics Internal Super Multi Drive Optical Drives GH24NSC0B",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lite-On 24X SATA Internal DVD+/-RW Drive Optical Drive IHAS124-14",
                            Price = 14.949999999999999
                        });
                });

            modelBuilder.Entity("PCconfiguration.Models.Cooling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Coolings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cooler Master Hyper 212 Evo",
                            Price = 28.699999999999999
                        },
                        new
                        {
                            Id = 2,
                            Name = "Noctua NH-D15",
                            Price = 89.950000000000003
                        },
                        new
                        {
                            Id = 3,
                            Name = "be quiet! Dark Rock 4",
                            Price = 74.849999999999994
                        },
                        new
                        {
                            Id = 4,
                            Name = "Corsair H150i",
                            Price = 170.52000000000001
                        },
                        new
                        {
                            Id = 5,
                            Name = "NZXT Kraken X62",
                            Price = 125.98999999999999
                        });
                });

            modelBuilder.Entity("PCconfiguration.Models.CpuCooling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CpuCoolings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Corsair H115i RGB Platinum",
                            Price = 68.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "EVGA CLC 240",
                            Price = 200.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cooler Master MA410M",
                            Price = 113.59
                        },
                        new
                        {
                            Id = 4,
                            Name = "Corsair H60 (2018)",
                            Price = 104.34999999999999
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cooler Master MasterLiquid ML360R",
                            Price = 280.0
                        });
                });

            modelBuilder.Entity("PCconfiguration.Models.GraphicsCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("GraphicsCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NVIDIA Titan RTX",
                            Price = 2499.9899999999998
                        },
                        new
                        {
                            Id = 2,
                            Name = "NVIDIA GeForce RTX 2080 Ti",
                            Price = 1229.95
                        },
                        new
                        {
                            Id = 3,
                            Name = "NVIDIA Titan Xp",
                            Price = 1779.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "NVIDIA GeForce GTX 1080 Ti",
                            Price = 699.87
                        },
                        new
                        {
                            Id = 5,
                            Name = "AMD Radeon VII",
                            Price = 549.99000000000001
                        });
                });

            modelBuilder.Entity("PCconfiguration.Models.HardDrive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("HardDrives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Seagate BarraCuda",
                            Price = 39.939999999999998
                        },
                        new
                        {
                            Id = 2,
                            Name = "Toshiba X300",
                            Price = 170.96000000000001
                        },
                        new
                        {
                            Id = 3,
                            Name = "Samsung 970 Evo Plus SSD",
                            Price = 108.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "WD Black SN750 NVMe SSD",
                            Price = 81.989999999999995
                        },
                        new
                        {
                            Id = 5,
                            Name = "Samsung 970 Pro",
                            Price = 304.44
                        });
                });

            modelBuilder.Entity("PCconfiguration.Models.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Motherboards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gigabyte Z390 Designare",
                            Price = 269.99000000000001
                        },
                        new
                        {
                            Id = 2,
                            Name = "ASRock Z390 Phantom Gaming ITX",
                            Price = 179.99000000000001
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gigabyte Z390 Gaming X",
                            Price = 139.99000000000001
                        },
                        new
                        {
                            Id = 4,
                            Name = "ASRock H370M Pro4",
                            Price = 84.989999999999995
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gigabyte X299X Designare 10G",
                            Price = 599.99000000000001
                        });
                });

            modelBuilder.Entity("PCconfiguration.Models.OperatingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Windows 10 Home",
                            Price = 139.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Windows 10 Pro",
                            Price = 199.99000000000001
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chalet Operating System",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ubuntu OS",
                            Price = 150.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Linux Mint",
                            Price = 89.989999999999995
                        });
                });

            modelBuilder.Entity("PCconfiguration.Models.PowerSupply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PowerSupplies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bitfenix BF450G",
                            Price = 60.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Seasonic SSR-600TL",
                            Price = 242.43000000000001
                        },
                        new
                        {
                            Id = 3,
                            Name = "Seasonic SSR-750PX",
                            Price = 148.99000000000001
                        },
                        new
                        {
                            Id = 4,
                            Name = "Corsair AX850",
                            Price = 239.99000000000001
                        },
                        new
                        {
                            Id = 5,
                            Name = "Corsair AX1000",
                            Price = 269.98000000000002
                        });
                });

            modelBuilder.Entity("PCconfiguration.Models.Processor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Processors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AMD RYZEN 9 3950X",
                            Price = 750.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "INTEL CORE I9-7980XE",
                            Price = 1225.3399999999999
                        },
                        new
                        {
                            Id = 3,
                            Name = "INTEL CORE I9-9980XE",
                            Price = 2406.7199999999998
                        },
                        new
                        {
                            Id = 4,
                            Name = "AMD RYZEN THREADRIPPER 3960X",
                            Price = 1564.75
                        },
                        new
                        {
                            Id = 5,
                            Name = "INTEL CORE I9-9900KS",
                            Price = 1129.0
                        });
                });

            modelBuilder.Entity("PCconfiguration.Models.Ram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Rams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CORSAIR VENGEANCE LED 16GB (2x8GB) DDR4 3000MHz C15 Desktop Memory - Blue LED",
                            Price = 179.99000000000001
                        },
                        new
                        {
                            Id = 2,
                            Name = "G.SKILL TridentZ RGB Series 16GB (2 x 8GB) 288-Pin DDR4 3000MHz (PC4 24000)",
                            Price = 89.989999999999995
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kingston Technology ValueRAM 16GB 2400MHz DDR4 ECC CL17 DIMM 2Rx8",
                            Price = 138.99000000000001
                        },
                        new
                        {
                            Id = 4,
                            Name = "4Gb 1866Mhz Ddr3 Cl10 Hyperx Fury Series 2 Pack",
                            Price = 74.370000000000005
                        },
                        new
                        {
                            Id = 5,
                            Name = "Corsair Dominator Platinum RGB 32GB (4x8GB) DDR4 3200 (PC4-25600)",
                            Price = 229.99000000000001
                        });
                });

            modelBuilder.Entity("PCconfiguration.Models.SoundCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SoundCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Creative Sound Blaster Audigy PCIe RX 7.1 Sound Card with High Performance Headphone Amp",
                            Price = 300.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "ASUS Sound Card Essence STX II",
                            Price = 106.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Creative 70SB174000000 Sound BlasterX AE-5 Hi-Resolution PCIe Gaming Sound Card",
                            Price = 238.99000000000001
                        },
                        new
                        {
                            Id = 4,
                            Name = "ASUS XONAR SE 5.1 Channel 192kHz/24-bit Hi-Res 116dB SNR PCIe Gaming Sound Card",
                            Price = 72.650000000000006
                        },
                        new
                        {
                            Id = 5,
                            Name = "FiiO E10K USB DAC and Headphone Amplifier (Black)",
                            Price = 144.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
